name = "LocalProjections"
uuid = "efdfa943-00bc-4a77-b5e5-4fa47d4501d1"
authors = ["Joe Saia <joe5saia@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
